recommendations ={1:[
       "Take a deep breath and smile.",
    "Blink slowly and rest your eyes.",
    "Stretch your arms overhead.",
    "Roll your shoulders gently.",
    "Sit straight and adjust your posture.",
    "Rest your palms on your lap.",
    "Loosen your fingers and wrists.",
    "Look away from the screen for 15 seconds.",
    "Wiggle your toes gently.",
    "Close your eyes for 10 seconds.",
    "Take a slow sip of water.",
    "Rotate your neck in small circles.",
    "Stretch your hands toward the ceiling.",
    "Place your feet flat on the floor.",
    "Gently massage your temples.",
    "Unclench your jaw.",
    "Look at something green in your room.",
    "Loosen your shoulders and drop them.",
    "Smile intentionally.",
    "Rest your hands and breathe slowly.",
    "Tilt your head left and right gently.",
    "Adjust your chair for comfort.",
    "Check if you're slouching — correct it.",
    "Place one hand on your stomach and breathe.",
    "Gently close your eyes and count to five."
],
    2:[
    "Stand up and do a quick body stretch.",
    "Listen to a calming instrumental track.",
    "Walk to a window and gaze outside.",
    "Move your neck in wide circles.",
    "Rub your hands together for warmth.",
    "Practice breathing: inhale 4s, hold 4s, exhale 4s.",
    "Take 2 minutes to reorganize your desk.",
    "Gently stretch your legs under the table.",
    "Hold a warm object and focus on its feel.",
    "Slowly sip a hot drink.",
    "Lower screen brightness temporarily.",
    "Play soft white noise in the background.",
    "Shake your hands to release tension.",
    "Visualize a peaceful place for 30 seconds.",
    "Use a hand grip or stress ball briefly.",
    "Rub your forehead and cheeks lightly.",
    "Change your sitting posture entirely.",
    "Read one inspiring quote from your collection.",
    "Walk slowly around the room for 1 minute.",
    "Check and improve your posture.",
    "Tap your fingers rhythmically on the desk.",
    "Do ankle circles under your chair.",
    "Hold your shoulders tight for 5s, then release.",
    "Clap your hands softly 5 times.",
    "Play a 1-minute nature sound clip."
],
    3:[
    "Take a 3-minute mindful break.",
    "Walk to another room and return slowly.",
    "Follow a breathing video or audio.",
    "Play a relaxing track and close your eyes.",
    "Do 5 deep inhale–exhale cycles.",
    "Gaze at a nature image for 1 minute.",
    "Watch a 1-minute calming YouTube clip.",
    "Turn away from your screen and sit quietly.",
    "Open a window and feel the air.",
    "Use a guided meditation app for 2 mins.",
    "Write one positive affirmation.",
    "Do 10 slow shoulder shrugs.",
    "Touch your toes (or reach toward them).",
    "Squeeze your fists tightly, then release.",
    "Journal one sentence about how you feel.",
    "Lie down briefly if possible.",
    "Dim the lights or screen for 2 minutes.",
    "Take 5 full breaths while focusing on your heartbeat.",
    "Reposition your desk lamp for less glare.",
    "Tidy up one item near your workspace.",
    "Turn on ambient background music.",
    "Close your eyes and visualize a peaceful forest.",
    "Read a short calming paragraph from your notes.",
    "Play with a fidget toy or pen.",
    "Stand up and shake out your limbs."
],
    4:[
    "Take a 5-minute screen break.",
    "Leave your desk and go to a new room.",
    "Do a 5-minute body scan meditation.",
    "Play a nature sounds playlist for 5 minutes.",
    "Lie down in a quiet place briefly.",
    "Drink a full glass of water slowly.",
    "Watch a calming visualization video.",
    "Use a mobile meditation timer for 5 minutes.",
    "Sit silently and close your eyes.",
    "Write 3 things you’re grateful for.",
    "Contact a friend with a calm message.",
    "Put on noise-canceling headphones.",
    "Write down how you feel in 3 words.",
    "Do a yoga breathing technique.",
    "Use a calming desktop app (if installed).",
    "Repeat a personal mantra aloud 5 times.",
    "Clean up a small area of your desk.",
    "Turn off all notifications for 10 minutes.",
    "Put your phone away temporarily.",
    "Move to a different sitting location.",
    "Turn off screen and sit in total silence.",
    "Stretch every part of your body gently.",
    "Lay your head on your desk and rest.",
    "Focus on your breath and count each one.",
    "Do a visualization of a beach walk."
],
    5:[
    "Immediately step away from your workspace.",
    "Take a 10-minute full break.",
    "Leave the room and go outside if possible.",
    "Do a full guided meditation session.",
    "Contact a trusted friend or support person.",
    "Close your laptop and sit in silence.",
    "Lie down in a quiet, darkened room.",
    "Turn off all devices temporarily.",
    "Write freely in a journal for 5 minutes.",
    "Play a 10-minute relaxing playlist.",
    "Take a power nap if possible.",
    "Watch a peaceful nature documentary.",
    "Do a breathing exercise with music.",
    "Use a stress-relief mobile app.",
    "Do a 5-minute mindfulness routine.",
    "Change clothes into something more comfortable.",
    "Sit on the floor and relax your body entirely.",
    "Turn off lights and close your eyes.",
    "Do a gratitude or hope visualization.",
    "Breathe in through your nose and sigh out loud.",
    "Take a quick walk outside the house or room.",
    "Sit with your pet or favorite object.",
    "Use aromatherapy (if available).",
    "Listen to a favorite song from childhood.",
    "Talk to a close friend or family member."
]
}